# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
  # 1950s
  # Apogee
  # Coffee
  # Dark
  # Earth
  # Forest
  # Strawberry
  # Ocean
  # Minimal (modern)
  # Classic (original Academic v1 style)
  # Rose (traditional serif)
  # Mr Robot (futuristic)
  # Cyberpunk (hacker style)
  # Native: use device fonts for maximum performance
appearance:
  theme_day: Mr Robot
  theme_night: Mr Robot
  font: Minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo academic resume theme powered by Wowchemy website builder.'
    twitter: 'wowchemy'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Freddy Seo.'
    # This work is licensed under {license}
    # license:
    #   enable: true
    #   allow_derivatives: false
    #   share_alike: true
    #   allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: true
  diagram:
    enable: true
  privacy_pack:
    enable: true
  docs_section_pager:
    enable: true
  repository:
    url: 'https://github.com/wdragj/wdragj.netlify.app'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    # Choose a provider: giscus, disqus, commento, or '' to disable commenting
    provider: 'disqus'
    disqus:
      # Paste the shortname from your Disqus dashboard.
      shortname: 'wdragj'
      # Show comment count in page header? (true/false)
      show_count: true
    commento:
      # If you self-host Commento, enter your custom Commento URL here.
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15
  icon:
    pack:
      ai: true

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
